Fix bug: If there are too many different concentrations in conc colum…
TangSoftwareLab/SynergyFinderWeb pull request #10
Opened 2023-02-22 14:55 UTC by shuyuzheng

If there are too many different concentrations in conc column for one block, the imputation causes a issue

2023-02-22 14:57 UTC, JehadAldahdooh requested changes

2023-02-22 14:57 UTC, JehadAldahdooh commented on server.R
> +                    "There are too many (more than 20) different concentrations in the '", i, "' column for block ",
test

2023-02-22 14:57 UTC, JehadAldahdooh commented on server.R
> +                  stop(
test

2023-02-22 14:58 UTC, jtang920 commented on server.R
> +                dosage <- annot[, c("block_id", i)] %>%
test by JT

2023-02-22 14:58 UTC, JehadAldahdooh commented on server.R
> +                    "There are too many (more than 20) different concentrations in the '", i, "' column for block ",
done

2023-02-22 14:58 UTC, shuyuzheng commented on server.R
> +                    "There are too many (more than 20) different concentrations in the '", i, "' column for block ",
done

2023-02-22 14:59 UTC, shuyuzheng commented on server.R
> +                dosage <- annot[, c("block_id", i)] %>%
Done

2023-02-22 15:23 UTC, jtang920 commented
There is some problems when loading this file. I got the same error message even though the data has less than 10 concentrations.
[ONEILMatrix_Test.xlsx](https://github.com/TangSoftwareLab/SynergyFinderWeb/files/10805384/ONEILMatrix_Test.xlsx)

2023-02-23 09:38 UTC, shuyuzheng commented on server.R
> +            } else if (length(concs) == 2) {
Since we are using the same threshold of number of concs for both 2-drug combo and multidrug combo. We can remove this "else if" part to reduce the code size.

2023-02-23 09:39 UTC, shuyuzheng commented on server.R
> +          } else if (length(concs) == 2) {
Since we are using the same threshold of number of concs for both 2-drug combo and multidrug combo. We can remove this "else if" part to reduce the code size.

2023-02-23 10:00 UTC, shuyuzheng commented on server.R
> +            } else if (length(concs) == 2) {
Done

2023-02-23 10:00 UTC, shuyuzheng commented on server.R
> +          } else if (length(concs) == 2) {
Done

2023-02-23 10:02 UTC, merged